services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - my_network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - my_network
  monitoring:
    build: .
    container_name: monitoring
    depends_on:
      - grafana
    networks:
      - my_network

networks:
  my_network:
    driver: bridge