services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
