{
 "title": "Rainer 8Q",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "chipname", "query": "${VAR_CHIPNAME}" },
   {
    "name": "qubit",
    "label": "Qubit",
    "query": "SELECT qubit_table.name FROM qubit_table INNER JOIN qubit_chip_table ON qubit_table.chip_id = qubit_chip_table.id WHERE qubit_chip_table.name = '${chipname}'"
   },
   { "name": "partition", "query": "${VAR_PARTITION}" }
  ]
 },
 "panels": [
  {
   "type": "nodeGraph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name as id,\r\n  name as title,\r\n  t1 as mainstat,\r\n  t2 as detail__t2,\r\n  t2_spin_echo as detail__t2_echo,\r\n  gate_fidelity as detail__gate_fidelity,\r\n  assignment_fidelity as detail__assignment_fidelity,\r\n  gate_fidelity as secondarystat\r\nFROM qubit_table\r\nWHERE $__timeFilter(datetime) AND \r\n  chip_id = (SELECT id FROM qubit_chip_table WHERE name = '${chipname}' ORDER BY id DESC LIMIT 1)\r\nORDER BY name"
    },
    {
     "rawSql": "SELECT id as id,\r\n  qubit1 as source,\r\n  qubit2 as target,\r\n  gate_fidelity as mainStat\r\n  FROM qubit_pair_table WHERE chip_id = (\r\n    SELECT id FROM qubit_chip_table WHERE name = '${chipname}' ORDER BY id DESC LIMIT 1\r\n  )"
    }
   ]
  },
  { "title": "Queue Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "slurm_node_count_per_state{instance=\"localhost:9092\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_partition_job_state_total{partition=\"$partition\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Mixing Chamber Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mK" } },
   "targets": [
    {
     "rawSql": "SELECT value, datetime AS \"time\" FROM temperature WHERE (channel = 6 AND $__timeFilter(datetime)) "
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, datetime AS \"time\" FROM temperature WHERE (channel = 6 AND $__timeFilter(datetime)) ORDER BY id DESC LIMIT 1 "
    }
   ]
  },
  { "title": "Single Qubit Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Coherence Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "SELECT qubit_table.t1 as \"T1\", qubit_table.t2 as \"T2\", qubit_table.t2_spin_echo as \"T2 Echo\", qubit_table.datetime as \"time\"\r\nFROM qubit_table\r\nINNER JOIN qubit_chip_table ON qubit_table.chip_id = qubit_chip_table.id\r\nWHERE qubit_table.name = '${qubit}'\r\n  AND qubit_chip_table.name = '${chipname}'\r\n  AND $__timeFilter(qubit_table.datetime)\r\nORDER BY qubit_table.id DESC"
    }
   ]
  },
  {
   "title": "Fidelities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT qubit_table.assignment_fidelity as \"Assignment Fidelity\", qubit_table.gate_fidelity as \"1Q Gate Fidelity\", qubit_table.datetime as \"time\"\r\nFROM qubit_table\r\nINNER JOIN qubit_chip_table ON qubit_table.chip_id = qubit_chip_table.id\r\nWHERE qubit_table.name = '${qubit}'\r\n  AND qubit_chip_table.name = '${chipname}'\r\n  AND $__timeFilter(qubit_table.datetime)\r\nORDER BY qubit_table.id DESC"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT name as \"Qubit ID\",\r\n  t1 as \"T1\",\r\n  t2 as \"T2\",\r\n  t2_spin_echo as \"T2 Echo\",\r\n  assignment_fidelity as \"Assignment Fidelity\",\r\n  gate_fidelity as \"1Q Gate Fidelity\"\r\nFROM qubit_table\r\nWHERE $__timeFilter(datetime) AND\r\n  chip_id = (SELECT id FROM qubit_chip_table WHERE name = '${chipname}' ORDER BY id DESC LIMIT 1)\r\nORDER BY name"
    }
   ]
  }
 ]
}